apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:5.0
          ports:
            - containerPort: 9000
            - containerPort: 12201
          env:
            - name: GRAYLOG_PASSWORD_SECRET
              value: somepasswordpepper
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: http://localhost:9000/
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              value: http://elasticsearch.default:9999
            - name: GRAYLOG_MONGODB_URI
              value: mongodb://mongodb.default:27017/graylog