scrape_configs:
  - job_name: "spring-actuator"
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
    - targets: ["bookmarkservice:8080", "fileservice:8082", "authservice:8081"]
  - job_name: postgres
    static_configs:
    - targets: ["postgres-exporter:9187"]

