apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgresql-claim0
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/Users/petr/Documents/7sem/java7sem/data"