apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              value: digitalbookmark
            - name: POSTGRES_USER
              value: digitalbookmark
            - name: POSTGRES_PASSWORD
              value: postgrePass
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-claim0
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgresql-claim0
          persistentVolumeClaim:
            claimName: postgresql-claim0