apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: prometheus
  name: prometheus
spec:
  selector:
    matchLabels:
      operator-prometheus: "true"
  endpoints:
    - interval: 30s
      targetPort: 9090
      path: /metrics
  namespaceSelector:
    any: true
