apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-service
          image: auth-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8081
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: "jdbc:postgresql://postgresql:5432/digitalbookmark"
            - name: POSTGRES_USER
              value: "digitalbookmark"
            - name: POSTGRES_PASS
              value: "postgrePass"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"